<?xml version="1.0" encoding="utf-8"?>

<!--
  Description of the ROSbot 3 robot.

  Author: Guilherme Teixeira Caldana
-->

<robot name="rosbot3" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find rosbot3_description)/urdf/ugv02.xacro" />

  <!-- Dimensions of the camera base -->
  <xacro:property name="camera_vertical_base_length" value="${20 * M}" />
  <xacro:property name="camera_vertical_base_width" value="${3 * M}" />
  <xacro:property name="camera_vertical_base_height" value="${70 * M}" />

  <xacro:property name="camera_horizontal_base_length" value="${35 * M}" />
  <xacro:property name="camera_horizontal_base_width" value="${3 * M}" />
  <xacro:property name="camera_horizontal_base_height" value="${20 * M}" />

  <!-- Dimensions of the camera OAK-D Lite-->
   <!-- https://shop.luxonis.com/products/oak-d-lite-1?variant=42583102456031 -->
  <xacro:property name="camera_length" value="${17.5 * M}" />
  <xacro:property name="camera_width" value="${91 * M}" />
  <xacro:property name="camera_height" value="${28 * M}" />


  <!-- Dimensions of the lidar RPLIDAR C1
   contained in this link 
   https://bucket-download.slamtec.com/2d4664be9f9f5c748f3b608f2cf1862962b168eb/SLAMTEC_rplidar_datasheet_C1_v1.1_en.pdf-->
 
  <xacro:property name="lidar_base_side" value="${55.6 * M}" />
  <xacro:property name="lidar_base_height" value="${23.1 * M}" />

  <xacro:property name="lidar_radius" value="${27 * M}" />
  <xacro:property name="lidar_height" value="${18.2 * M}" />

  <!-- Dimensions of the antenna-->
  <!-- <xacro:property name="antenna_radius" value="${5 * M}" />
  <xacro:property name="antenna_height" value="${80 * M}" /> -->

  <!-- Building the vertical part of the camera base for both sides-->
  <xacro:solid_block
    name="camera_vertical_right_base"
    size_x="${camera_vertical_base_length}"
    size_y="${camera_vertical_base_width}"
    size_z="${camera_vertical_base_height}"
  />

  <xacro:solid_block
    name="camera_vertical_left_base"
    size_x="${camera_vertical_base_length}"
    size_y="${camera_vertical_base_width}"
    size_z="${camera_vertical_base_height}"
  />

  <!-- Joining the vertical camera base to the body of the robot for both sides-->
  <xacro:joint_fixed
    parent="body"
    child="camera_vertical_left_base"  
    y="${0.2 * body_width}"
    z="${0.5 * (body_height + camera_vertical_base_height)}"
  />

  <xacro:joint_fixed
    parent="body"
    child="camera_vertical_right_base"
    
    y="${-0.2 * body_width}"
    z="${0.5 * (body_height + camera_vertical_base_height)}"
  />

  <!-- Building the horizontal part of the camera base for both sides-->
  <xacro:solid_block
    name="camera_horizontal_left_base"
    size_x="${camera_horizontal_base_length}"
    size_y="${camera_horizontal_base_width}"
    size_z="${camera_horizontal_base_height}"
  />

  <xacro:solid_block
    name="camera_horizontal_right_base"
    size_x="${camera_horizontal_base_length}"
    size_y="${camera_horizontal_base_width}"
    size_z="${camera_horizontal_base_height}"
  />

  <!-- Joining the horizontal camera base to the vertical camera base for both sides-->
  <xacro:joint_fixed
    parent="camera_vertical_left_base"
    child="camera_horizontal_left_base"
    x="${camera_vertical_base_length}"
    z="${0.5 * (camera_vertical_base_height - camera_horizontal_base_height)}"
  />

  <xacro:joint_fixed
    parent="camera_vertical_right_base"
    child="camera_horizontal_right_base"
    x="${camera_vertical_base_length}"
    z="${0.5 * (camera_vertical_base_height - camera_horizontal_base_height)}"
  />

  <!-- Building the camera structure -->
  <xacro:solid_block
    name="camera"
    size_x="${camera_length}"
    size_y="${camera_width}"
    size_z="${camera_height}"
  />

  <!-- Joining the camera to the horizontal camera base-->
  <xacro:joint_fixed
    parent="camera_horizontal_right_base"
    child="camera"
    x="${0.5 * camera_length}"
    y="${0.5*camera_width - 8.9 * M}"
  />

  <!-- Creating the camera link -->
  <xacro:camera_link name="camera_front" />

  <!-- Joining the camera link to the camera's structure (block) -->
  <xacro:joint_fixed
    parent="camera"
    child="camera_front"
    x="${0.5 * camera_length}"
  />

  <!-- Building the lidar base structure -->
  <xacro:solid_block
    name="lidar_base"
    size_x="${lidar_base_side}"
    size_y="${lidar_base_side}"
    size_z="${lidar_base_height}"
  />

  <!-- Joining the lidar to the body of the robot-->
  <xacro:joint_fixed
    parent="body"
    child="lidar_base"
    z="${0.5 * (body_height + lidar_base_height)- 3.3*M}" 
    x="${0.2 * body_length}"
  />
<!-- I subtracted 3.3 in z because at the lidar datasheet, the height is 3.3 higher than
  in the ROSbot3 documentation. So I supposed that the lidar is a bit drownedin the robot surface.
-->

  <!-- Building the lidar structure -->
  <xacro:solid_cylinder
    name="lidar"
    length="${lidar_height}"
    radius="${lidar_radius}"
  />

  <!-- Joining the lidar to the body of the robot-->
  <xacro:joint_fixed
    parent="lidar_base"
    child="lidar"
    z="${0.5 * (lidar_base_height + lidar_height)}"
  />

  <!-- Creating the lidar/laser link -->
  <link name="laser" />

  <!-- Joining the lidar/laser link to the lidar's structure (cylinder) --> -->
  <xacro:joint_fixed
    parent="lidar"
    child="laser"
    z="${0.5 * lidar_height}"
  />

  <!-- Building the antenna structure -->
    <!-- <xacro:solid_cylinder
    name="antenna"
    length="${antenna_height}"
    radius="${antenna_radius}"
  /> -->

  <!-- Joining the antenna to the body of the robot-->
  <!-- <xacro:joint_fixed
    parent="body"
    child="antenna"
    x="${-0.45 * body_length}"
    y="${0.2 * body_width}"
    z="${0.5 * (body_height + antenna_height)}"
  /> -->
</robot>

<!-- PS: I commented the antenna because the lidar is geting its position in the rviz, so I don't know if it's worth to let it there. 
 Maybe it is a calibration issue. If you want to see with it, just uncomment the dimensions, the building of the solid_cylinder and the joints -->