<?xml version="1.0" encoding="utf-8"?>

<!--
  Description of the ROSbot 3 robot.

  Author: Guilherme Teixeira Caldana
-->

<robot name="rosbot3" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find rosbot3_description)/urdf/ugv02.xacro" />

  <!-- Dimensions of the camera base -->
  <xacro:property name="camera_vertical_base_length" value="${20 * M}" />
  <xacro:property name="camera_vertical_base_width" value="${3 * M}" />
  <xacro:property name="camera_vertical_base_height" value="${94 * M}" />

  <xacro:property name="camera_horizontal_base_length" value="${35 * M}" />
  <xacro:property name="camera_horizontal_base_width" value="${3 * M}" />
  <xacro:property name="camera_horizontal_base_height" value="${20 * M}" />

  <!-- Dimensions of the camera -->
  <xacro:property name="camera_length" value="${20 * M}" />
  <xacro:property name="camera_width" value="${80 * M}" />
  <xacro:property name="camera_height" value="${30 * M}" />

<!-- Dimensions of the lidar -->
  <xacro:property name="lidar_radius" value="${50 * M}" />
  <xacro:property name="lidar_height" value="${38 * M}" />

  <!-- Dimensions of the antenna-->
  <!-- <xacro:property name="antenna_radius" value="${5 * M}" />
  <xacro:property name="antenna_height" value="${80 * M}" /> -->

  <!-- Building the vertical part of the camera base for both sides-->
  <xacro:solid_block
    name="camera_vertical_right_base"
    size_x="${camera_vertical_base_length}"
    size_y="${camera_vertical_base_width}"
    size_z="${camera_vertical_base_height}"
  />

  <xacro:solid_block
    name="camera_vertical_left_base"
    size_x="${camera_vertical_base_length}"
    size_y="${camera_vertical_base_width}"
    size_z="${camera_vertical_base_height}"
  />

  <!-- Joining the vertical camera base to the body of the robot for both sides-->
  <xacro:joint_fixed
    parent="body"
    child="camera_vertical_left_base"
    x="${-0.3 * body_length}"
    y="${0.2 * body_width}"
    z="${0.5 * (body_height + camera_vertical_base_height)}"
  />

  <xacro:joint_fixed
    parent="body"
    child="camera_vertical_right_base"
    x="${-0.3 * body_length}"
    y="${-0.2 * body_width}"
    z="${0.5 * (body_height + camera_vertical_base_height)}"
  />

  <!-- Building the horizontal part of the camera base for both sides-->
  <xacro:solid_block
    name="camera_horizontal_left_base"
    size_x="${camera_horizontal_base_length}"
    size_y="${camera_horizontal_base_width}"
    size_z="${camera_horizontal_base_height}"
  />

  <xacro:solid_block
    name="camera_horizontal_right_base"
    size_x="${camera_horizontal_base_length}"
    size_y="${camera_horizontal_base_width}"
    size_z="${camera_horizontal_base_height}"
  />

  <!-- Joining the horizontal camera base to the vertical camera base for both sides-->
  <xacro:joint_fixed
    parent="camera_vertical_left_base"
    child="camera_horizontal_left_base"
    x="${camera_vertical_base_length}"
    z="${0.5 * (camera_vertical_base_height - camera_horizontal_base_height)}"
  />

  <xacro:joint_fixed
    parent="camera_vertical_right_base"
    child="camera_horizontal_right_base"
    x="${camera_vertical_base_length}"
    z="${0.5 * (camera_vertical_base_height - camera_horizontal_base_height)}"
  />

  <!-- Building the camera structure -->
  <xacro:solid_block
    name="camera"
    size_x="${camera_length}"
    size_y="${camera_width}"
    size_z="${camera_height}"
  />

  <!-- Joining the camera to the horizontal camera base-->
  <xacro:joint_fixed
    parent="camera_horizontal_right_base"
    child="camera"
    x="${0.5 * camera_length}"
    y="${0.5*camera_width - 3.4 * M}"
  />

  <!-- Creating the camera link -->
  <xacro:camera_link name="camera_front" />

  <!-- Joining the camera link to the camera's structure (block) -->
  <xacro:joint_fixed
    parent="camera"
    child="camera_front"
    x="${0.5 * camera_length}"
  />

  <!-- Building the lidar structure -->
  <xacro:solid_cylinder
    name="lidar"
    length="${lidar_height}"
    radius="${lidar_radius}"
  />

  <!-- Joining the lidar to the body of the robot-->
  <xacro:joint_fixed
    parent="body"
    child="lidar"
    z="${0.5 * (body_height + lidar_height)}"
  />

  <!-- Creating the lidar/laser link -->
  <link name="laser" />

  <!-- Joining the lidar/laser link to the lidar's structure (cylinder) --> -->
  <xacro:joint_fixed
    parent="lidar"
    child="laser"
    z="${0.5 * lidar_height}"
  />

  <!-- Building the antenna structure -->
    <!-- <xacro:solid_cylinder
    name="antenna"
    length="${antenna_height}"
    radius="${antenna_radius}"
  /> -->

  <!-- Joining the antenna to the body of the robot-->
  <!-- <xacro:joint_fixed
    parent="body"
    child="antenna"
    x="${-0.45 * body_length}"
    y="${0.2 * body_width}"
    z="${0.5 * (body_height + antenna_height)}"
  /> -->
</robot>

<!-- PS: I commented the antenna because the lidar is geting its position in the rviz, so I don't know if it's worth to let it there. 
 Maybe it is a calibration issue. If you want to see with it, just uncomment the dimensions, the building of the solid_cylinder and the joints -->