<?xml version="1.0" encoding="utf-8"?>

<!--
  Description of the Waveshare UGV02 mobile base upon which ROSbot 3 is built.

  Author: Guilherme Teixeira Caldana
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find ros_commons)/urdf/domain.xacro"/>

  <xacro:property name="M" value="0.001"/>

  <xacro:property name="overall_height" value="${103 * M}"/>



  <!-- Using standard wheels values -->
  <xacro:property name="ground_clearance" value="${23 * M}"/>
  <xacro:property name="wheel_diameter" value="${84.0 * M}"/>
  <xacro:property name="wheel_radius" value="${0.5 * wheel_diameter}"/>
  <xacro:property name="wheelbase" value="${106.0 * M}"/>

  <!-- Value not defined. Random value put from image -->
  <xacro:property name="wheel_thickness" value="${25 * M}"/>

  <!-- Distance between intern part of both wheels in the same axe -->
  <xacro:property name="wheel_separation" value="${233.0 * M - 2* wheel_thickness}"/>
  
  <xacro:property name="body_length" value="${200.0 * M}"/>
  <xacro:property name="body_width" value="${233.0 * M - 2 * wheel_thickness}"/>
  <xacro:property name="body_height" value="${103.0 * M - ground_clearance }"/>


  <!-- <xacro:property name="fender_length" value="${200.0 * M}"/>
  <xacro:property name="fender_thickness" value="${3.0 * M}"/>
  <xacro:property name="fender_top_gap" value="${1.0 * M}"/>
  <xacro:property name="fender_side_gap" value="${5.0 * M}"/>

  <xacro:property name="fender_top_width" value="${body_width + 2.0 * (wheel_thickness * 0.75)}"/>
  <xacro:property name="fender_side_width" value="${wheel_radius + fender_thickness + fender_top_gap}"/>

  <xacro:property name="fender_side_y_offset" value="${0.5 * (fender_top_width + fender_thickness)}"/>
  <xacro:property name="fender_side_z_offset" value="${0.5 * (fender_thickness - fender_side_width)}"/> --> 

  <xacro:property name="wheel_axle_z_offset" value="${wheel_radius - 0.5 * body_height - ground_clearance}"/>

  <xacro:macro
    name="wheels"
    params="position"
  >
    <xacro:solid_cylinder
      name="wheel_${position}_left"
      length="${wheel_thickness}"
      radius="${wheel_radius}"
      roll="${90.0 * DEG}"
    />

    <xacro:solid_cylinder
      name="wheel_${position}_right"
      length="${wheel_thickness}"
      radius="${wheel_radius}"
      roll="${90.0 * DEG}"
    />

    <xacro:solid_cylinder
      name="wheel_${position}_axle"
      length="${wheel_separation}"
      radius="0.005"
      roll="${90.0 * DEG}"
    />

    <xacro:joint_continuous
      name="joint_wheel_${position}_left"
      parent="wheel_${position}_axle"
      child="wheel_${position}_left"
      y="${(wheel_separation + wheel_thickness) * 0.5}"
      axis="0 1 0"
    />

    <xacro:joint_continuous
      name="joint_wheel_${position}_right"
      parent="wheel_${position}_axle"
      child="wheel_${position}_right"
      y="${(wheel_separation + wheel_thickness) * -0.5}"
      axis="0 1 0"
    />
  </xacro:macro>

  <xacro:wheels position="front"/>
  <xacro:wheels position="rear"/>

  <xacro:solid_block
    name="body"
    size_x="${body_length}"
    size_y="${body_width}"
    size_z="${body_height}"
  />

  <xacro:joint_fixed
    parent="body"
    child="wheel_front_axle"
    x="${0.5 * wheelbase}"
    z="${wheel_axle_z_offset}"
  />

  <xacro:joint_fixed
    parent="body"
    child="wheel_rear_axle"
    x="${-0.5 * wheelbase}"
    z="${wheel_axle_z_offset}"
  />

  <link name="base_link"/>
  <xacro:joint_fixed
    parent="base_link"
    child="body"
    z="${ground_clearance + 0.5 * body_height}"
  />
</robot>
